# config/_default/config.toml
baseURL = 'https://www.guyu.me/'
title = '顾宇的博客'

defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]