# config/_default/config.toml
baseURL = 'https://wwww.guyu.me/'
title = '顾宇的博客'
theme = "congo"

defaultContentLanguage = 'zh'
enableRobotsTXT = true
paginate = 10
summaryLength = 0
hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS", "JSON"]