
# config/_default/languagues.zh.toml

languageCode = "zh"
languageName = "Chinese-Simplified"
weight = 1

[params]
  displayName = "ZH"
  htmlCode = "zh"
  rtl = false

# Language-specific parameters go here
[params.author]
  name = "顾宇"

[author]
  image = "/img/author.jpg"
  headline = ""
  bio = "www.guyu.me"
  links = [
    { github = "https://github.com/wizardbyron" }
  ]