# config/_default/markup.toml

[tableOfContents]
  startLevel = 2
  endLevel = 4

[highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  noHl = false
  style = 'xcode'
  tabWidth = 4