[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "博客列表"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "博客标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "实践指南"
  url = "/guides"
  weight = 40

[[main]]
  name = "个人简介"
  pageRef = "about"
  weight = 50
