[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "博客文章"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "文章分类"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "实践指南"
  url = "/guide"
  weight = 40

[[main]]
  name = "关于我"
  pageRef = "about"
  weight = 50
