[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "关于我"
  pageRef = "about"
  weight = 20

[[main]]
  name = "演讲和分享"
  pageRef = "talks"
  weight = 30

[[main]]
  name = "博客列表"
  pageRef = "blog"
  weight = 40

[[main]]
  name = "博客标签"
  pageRef = "tags"
  weight = 50
