baseURL = 'https://wwww.guyu.me/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
title = '顾宇的博客'
theme = "congo"

hasCJKLanguage = true

[author]
  name = "顾宇"
  image = "/img/author.jpg"
  bio = "Stand Alone CompleX"
  links = [
    { linkedin = "https://linkedin.com/in/wizardbyron" },
    { github = "https://github.com/wizardbyron" }
  ]

[params]
  darkMode = "auto"
  darkToggle = true
  colorScheme = "slate"

[params.homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[params.article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/wizardbyron/wizardbyron.github.io/tree/main/content"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = true

[menu]
[[menu.main]]
  name = "主页"
  url = "/"
  weight = 10

[[menu.main]]
  name = "博客文章"
  pageRef = "blog"
  weight = 20

[[menu.main]]
  name = "标签分类"
  pageRef = "tags"
  weight = 30

[[menu.main]]
  name = "实践指南"
  url = "/guide"
  weight = 40

[[menu.main]]
  name = "关于我"
  pageRef = "about"
  weight = 50
